# Generated by Django 4.1.13 on 2024-06-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legendary_animals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
