# Generated by Django 4.2.13 on 2024-05-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='about',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
